### ISSUE TITLE
"Simple" mode for pricing

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#107]
### Description

Add a toggle for simple/advanced mode for host configuration. Simple should be the default.

## "Simple" Mode
Visible settings:
- accepting contracts
- address
- storage price
- egress price
- ingress price
- collateral multiplier
- DNS settings
- bandwidth settings

Calculated settings:
- max collateral
  - max collateral would be automatically calculated with the following formula: `12960 * storage price per byte/block * 1 TB * collateral multiplier` 
  - e.g. a storage price of `400 SC/TB/mo` (`92592592593 H/byte/block`)  and collateral multiplier of `2.0` would have a max collateral of `2400 SC`

Hidden settings:
- max duration
- contract price
- base RPC price
- sector access price
- price table validity
- registry settings
- account settings

## Advanced Mode
Would work as it does today. All fields are visible, no calculated fields

**Comment by alexfreska** [comment]
@n8maninger when toggling from advanced to simple would the hidden fields remain the same or get set to some default values, what should those defaults be?

**Comment by n8maninger** [comment]
> @n8maninger when toggling from advanced to simple would the hidden fields remain the same or get set to some default values, what should those defaults be?

I’m leaning towards leaving them untouched. What do you think?

**Comment by alexfreska** [comment]
Yeah I think thats the way to go, lets try that. If it ends up being confusing we could add some UX around edge cases, such as when someone switches to advanced mode changes advanced settings and then toggles back to basic view I could diff the hidden options with a set of defaults and add a warning.
