### ISSUE TITLE
Add network height to node page

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#114]
### Description

<img width="1676" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/a0ed3788-fb3b-4456-ac10-a68ceecac9c7">

Hostd - Blockchain windows should have the current network hight

### Version

0.1.0 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
@alexfreska `[GET] /state/host` has `startTime` https://api.sia.tech/hostd#32ef7651-c2c1-43c6-89d3-f17c188b4667

**Comment by n8maninger** [comment]
Closed by #178
