### ISSUE TITLE
Sync display in top left can't be seen (its to dark)

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#115]
### Current Behavior

Sync display status in top left can't be seen (its to dark)

<img width="277" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/0716a1fb-f0e0-492e-be6e-23fe66dd5007">

### Expected Behavior

it should be a lighter gray or white or some other color that is more readable.

### Version

0.1.0 Beta

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
Fixed by #141
