### ISSUE TITLE
Hostd  - Alert pop up window, if there are no alerts you might automaticly close it after say 5 sec.

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#116]
### Description

<img width="992" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/c5b87a13-5d15-48fe-b16a-d6cfe1b15c9b">

Hostd  - Alert pop-up window, if there are no alerts you might automatically close it after say 5 sec.

### Version

0.1.0 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
I think we'll stick to the manual close for now. We may revisit in the future as the UI changes, though.
