### ISSUE TITLE
UI choices should be remembered

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#118]
### Current Behavior

<img width="503" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/730576ee-0156-43a5-b7ff-ce3e3dad64b4">

The above underlined settings should be remembered.  But if I move to another page (say contracts) and then move back it resets them back to the default which is not always what is wanted if I have made changes.

### Expected Behavior

It should remember what the setting is changed to.

### Version

0.1.0 Beta

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
Fixed by #141
