### ISSUE TITLE
Freeze table headers on contract page

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#124]
### Description

In the contracts page, can the column headers be frozen so they don't disappear off the page when you scroll down? The same request also applies to the Volumes page.

### Version

v0.1.2

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04

### Anything else?

Client browser is Firefox on Windows 11.

**Comment by n8maninger** [comment]
Fixed by #141
