### ISSUE TITLE
Dashboard date range stuck showing July 23 - July 30

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#128]
### Current Behavior

home display screen seems to be stuck showing July 23 - July 30.  I was able to fix the issue by changing the display length from 7 days to 1 month and then back again.

### Expected Behavior

It should be 7 days from the current day but for some reason it got stuck.

### Version

V0.1.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by rdwild** [comment]
I find if I refresh the browser page for hosted, it updates the page but it does not seem to be doing that unless I do a browser page refresh.

**Comment by alexfreska** [comment]
hey @rdwild thanks for reporting this. It used to permanently get stuck but I fixed that a while back. Now the time range is fixed until refresh - I am making a fix so that the metrics are automatically refreshed at approximately the data interval, eg every 5 min.

**Comment by n8maninger** [comment]
Fixed by #141

**Comment by rdwild** [comment]
That should work.
