### ISSUE TITLE
HOSTD does not check existance of configured volumes 

### ISSUE THREAD

**Issue by serveriukai** [SiaFoundation/hostd#131]
### Current Behavior

Hostd 0.1.3 running native on mainnet on linux:

mounted two external usb disks:
/home/sia/disk1/data.dat 3.9TB
/home/sia/disk2/data.dat 3.9TB

During short life span of three days the second disk two times somehow un-bindmounted itself. Mounts unstability is clearly problem on my side, but thanks to it I'm now reporting unability to fix a problem at HOSTD.

First time simple command 'mount -a' was enough for hostd 0.1.2 to recognize remounted volume.

Now, on hostd 0.1.3 with volume remounted, readable and writable, and disk "not sleep" script successfully doing writes to it every 5 minutes, hostd refuse to recognize a volume. Web interface "Volumes":

/home/sia/disk1/data.dat  ready  83.89 MB / 3.90 TB  8  7  0  0
/home/sia/disk2/data.dat  unavailable  50.33 MB / 3.90 TB  0  0  0  0

I'm logging to /var/log/hostd at 'inform' level, do not see errors.
host pub key:  ed25519:4c14150661430c4f2b6fe654ee753fff574208f39b86f742dba09f6c4929230e

### Expected Behavior

Unmounted volumes should not be shown "ready" in web interface.
Hostd should recognize remounted volumes.

### Version

0.1.3

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

ubuntu 22.04

**Comment by serveriukai** [comment]
Volume was recognized after hostd restart.

**Comment by n8maninger** [comment]
The volume being unavailable until restart is expected behavior. 

Can you clarify what you mean by "Until restart hostd several hours was "offline", with responsive web interface still."? Was it only the volume being unavailable in `hostd` or was `hostd` not responding on the troubleshooter?

**Comment by serveriukai** [comment]
For better clarity I tried to reproduce.
Turned second volume disk (external) off. At the moment there is only empty mount directory without data.dat file.

Hostd is running uninterrupted: # systemctl status hostd
● hostd.service - hostd
     Loaded: loaded (/etc/systemd/system/hostd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-02 15:56:34 EEST; 3h 25min ago

Hostd web interface shows:
 /home/sia/disk2/data.dat  ready  29.36 MB / 3.90 TB  0  0  0  0

But mount directory is empty, disk is turned-off.

**Comment by n8maninger** [comment]
`/home/sia/disk2/data.dat` doesn't exist, but the volume shows as "ready"?

**Comment by serveriukai** [comment]
Exactly ↑↑↑
