### ISSUE TITLE
Volume shrink error

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/hostd#149]
### Current Behavior

Volume shrink action causes an error. Volume shrinks fine.

![image](https://github.com/SiaFoundation/hostd/assets/4835677/b5a97ccc-2820-48a1-a34d-09714698f846)

```
{"level":"info","ts":1692104125.842518,"logger":"volumes.shrinkVolume","caller":"storage/storage.go:354","msg":"migrated sectors","volumeID":2,"oldMaxSectors":7209,"newMaxSectors":6914,"count":239}
{"level":"error","ts":1692104126.0282094,"logger":"volumes.resize","caller":"storage/storage.go:785","msg":"failed to resize volume","volumeID":2,"error":"failed to expand volume metadata: transaction failed: cannot shrink volume to 6889 sectors, 25 sectors are in use: volume is not empty","stacktrace":"go.sia.tech/hostd/host/storage.(*VolumeManager).ResizeVolume.func1\n\tgo.sia.tech/hostd/host/storage/storage.go:785"}
```

### Expected Behavior

.

### Steps to Reproduce

1. Go to Volumes
2. Edit volume size to smaller one
3. Wait few seconds and check alters

### Version

v0.1.4

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Windows 11

**Comment by n8maninger** [comment]
Fixed by #151
