### ISSUE TITLE
Alert text cutoff

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#152]
### Current Behavior

![Screenshot 2023-08-18 at 9 23 53 AM](https://github.com/SiaFoundation/hostd/assets/5544150/fd67315b-c314-4722-8577-5a84c2bdda17)

### Expected Behavior

To see the full alert text

### Version

v0.1.4

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

All

**Comment by alexfreska** [comment]
Fixed https://github.com/SiaFoundation/hostd/pull/154
