### ISSUE TITLE
hostd.log is not logrotate friendly

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#161]
### Current Behavior

With the following log rotate configlet:
```
# rotate the Sia hostd logs
/var/lib/hostd/*/*.log /var/lib/hostd/hostd.log /var/log/hostd/*.log {
    notifempty
    missingok
    weekly
    compress
    rotate 4
}
```
Once logrotate rotates the log file, all logging stops.

### Expected Behavior

Either logging should continue to a new log file of the original name or there should be a postrotate command to send to hostd to kick-start the logging again. Perhaps some sort of sighup. It can be got round by using the `copytruncate` feature of logrotate but this is not nice and should only be used as a last resort.

### Version

v0.1.7

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

### Anything else?

At one point I think logging was logrotate-friendly as I had the line `copytruncate` commented out in my configlet, but this may be a hangup from the `siad` configlet.

**Comment by SAHU-01** [comment]
Hi there, may I contribute to this issue?
