### ISSUE TITLE
Only renew contract when previous is 100% used.

### ISSUE THREAD

**Issue by MaartenMees** [SiaFoundation/hostd#169]
### Description

Contracts keep renewing even when little storage is used. 
Low risked collateral but very high locked collateral.

Ex. 2ksc risked results in 4ksc locked in only a week
![Screenshot_20230913_215038_Chrome~3](https://github.com/SiaFoundation/hostd/assets/26173684/cea47ecd-c368-43d1-b901-bbaec359fe2c)
![Screenshot_20230913_215135_Chrome~3](https://github.com/SiaFoundation/hostd/assets/26173684/6e4e0ebd-f116-4e06-81e5-ade0c26e331e)

### Version

V0.1.7

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.03

**Comment by n8maninger** [comment]
We've adjusted the renewal logic in `renterd` to make sure contracts are less likely to be prematurely refreshed (https://github.com/SiaFoundation/renterd/pull/601). 

In addition, we're changing contract renewals in v2 so hosts can roll over funds into the new contract. That means hosts won't have to lock additional SC into a renewed contract if funds are left over in the old one. This is the real fix for this issue, but it's a way out.

**Comment by MaartenMees** [comment]
Great. Thx

**Comment by rdwild** [comment]
That is why it would be nice to be able to block a renter from re-renting on the contracts screen.  Maybe have it so the current contract would keep going until it expires but not allow a renewal  Renters have control over hosts, it be nice is hosts had a bit more control.

**Comment by MaartenMees** [comment]
I would suggest thar renter can add storage to contract or/and renew it for a while (min/max specified by host)

Maybe asking to much but can try :)

**Comment by n8maninger** [comment]
This will get better after the hardfork when hosts can roll collateral into the renewal
