### ISSUE TITLE
Support cancellation for volume actions

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#170]
### Description

Add API endpoints to cancel in progress volume create, resize, and remove operations.

**Comment by n8maninger** [comment]
#171 adds `DELETE /volumes/:id/cancel` to stop an in-progress action. @alexfreska, can you add it to the volume context menu when you get the chance? The menu items should be hidden/greyed out based on the volume's status. 

- When status is "ready" -- "Resize" and "Delete" 
- When status is "creating", "resizing", or "removing" -- "Cancel"

**Comment by alexfreska** [comment]
yep 👍🏼

**Comment by n8maninger** [comment]
Closed by #178
