### ISSUE TITLE
hostd_linux_amd64-0.2.0 refuse to recognize dataDir in hostd.yml

### ISSUE THREAD

**Issue by serveriukai** [SiaFoundation/hostd#175]
### Current Behavior

hostd-0.2.0 failed to start on linux with error message
```
FATAL        failed to decode config file        {"error": "yaml: unmarshal errors:\n  line 1: field dataDir not found in type config.Config"}
hostd.service: Main process exited, code=exited, status=1/FAILURE
hostd.service: Failed with result 'exit-code'.
```
Successfully started after removing first (dataDir) line from hostd.yml

### Expected Behavior

Properly read hostd.yml

### Version

v0.2.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
`dataDir` has been changed to `directory`. Sorry, missed that in the release notes.

**Comment by serveriukai** [comment]
should be corrected in README.md comming with download

**Comment by BHare1985** [comment]
I am getting this same error on debian 12 after following the 0.2 README. 
I changed `dataDir` to `directory` to no avail in the hostd.yml, what is the solution for 0.2 ?
