### ISSUE TITLE
Cache commonly used sectors in memory

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#18]
Add a configurable LRU cache for sectors. 

_Edit: add implementation details_

---

The cache needs to link the sector's root (`types.Hash256`) with the sector's data (`*[rhpv2.SectorSize]byte`). Older sectors should be ejected as more sectors are added. The cache should be disabled if the setting is zero. 

There are a couple of moving parts here. My recommendation is to start with a static LRU cache in the volume manager, write some tests, then move on to making it configured via the host's settings. Each part can be together or separate PRs.

### Part 1 - Add an LRU cache to the volume manager
1. Add the cache to the volume manager https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L63-L78
2. Check the cache for the sector root. If the sector does not exist in the cache, read it from disk, and add it. https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L844-L871
3. Add newly written sectors to the cache https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L901-L927 

### Part 2 - Make the cache size configurable
1. Add a new setting for the number of sectors to cache. An `int` or `uint32` is fine. Each sector is 4MiB. https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/settings/settings.go#L39-L76
2. Add the new setting to the database https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/persist/sqlite/init.sql#L184-L209
3. Add a migration to add the new column https://github.com/SiaFoundation/hostd/blob/master/persist/sqlite/migrations.go
4. Change the store methods to read and update the new column https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/persist/sqlite/settings.go#L17-L112
5. Pass the initial cache setting into the volume manager and initialize the cache https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L956-L979
6. Resize the cache when the setting changes. There are a few ways to do this. The least invasive is probably to add a `ResizeCache(sectors int) error` func to the volume manager and call it from the settings API handler. https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/api/endpoints.go#L116-L153

**Comment by SAHU-01** [comment]
Hi there, may I contribute to this issue?

**Comment by n8maninger** [comment]
Sure. The cache needs to link the sector's root (`types.Hash256`) with the sector's data (`*[rhpv2.SectorSize]byte`). Sectors should be ejected as more sectors are added. There are a couple of moving parts here. My recommendation is to start with a static LRU cache in the volume manager, write some tests, then move on to making it configured via the host's settings. They can be separate PRs if you feel it is best to split it up. Let me know if you have any questions or run into issues.


### Part 1 - Add an LRU cache to the volume manager
1. Add the cache to the volume manager https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L63-L78
2. Check the cache for the sector root https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L844-L871. If the sector does not exist in the cache, read it from disk, and add it.
3. Add newly written sectors to the cache https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L901-L927 


### Part 2 - Make the cache size configurable
1. Make the cache size configurable https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/settings/settings.go#L39-L76
2. Pass the cache setting/settings manager into the volume manager https://github.com/SiaFoundation/hostd/blob/16d5e8efc93fafeddb0b37b6b1e957d089c657ff/host/storage/storage.go#L956-L979
3. Check the setting for the maximum cache size when adding/ejecting sectors

**Comment by SAHU-01** [comment]
For part 2, point no. 5)Pass the initial cache setting into the volume manager and initialize the cache ; 
I believe I can omit this step as it's already done in part 1. What do you suggest?

**Comment by n8maninger** [comment]
You also need to load the value from the settings into the volume manager.
