### ISSUE TITLE
There should also be an alert if there is a smartdrive (smartctl in linux) failure.

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#186]
### Description

Since the whole point of a hostd device is to provide storage it would be nice if a smart HDD support event triggered an alert in the hosts to notify operators that there is an important event that needs to be attended to.  Ie: if a raid volume lost a drive, etc.

### Version

0.2.0

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by NickJH** [comment]
Isn't that the job of packages such as `smartmontools` in Linux? It can do all the alerting.

**Comment by javierxam** [comment]
Temp of drives is also a good metric to look at. I think it's a hoster job to care about but i think it'll improve network resilence if a smartctl data is provided in UI. I think may be better to create docs for educating the hosters about hdd health care

**Comment by rdwild** [comment]
I'm suggesting that hostd should be communicating with these apps and pop up an alert for certain things.  That way if there is a failure of the monitoring app (I'm thinking for some reason one of its emails doesn't come through) it's just another place to see alerts that are very germane to hostd.

**Comment by n8maninger** [comment]
This would be difficult to implement across operating systems, so we'll leave it to OS utilities for now.
