### ISSUE TITLE
Add Gitpod environment for user testing and contribution

### ISSUE THREAD

**Issue by Smartmind12** [SiaFoundation/hostd#190]
### Description

Gitpod environment allows you to view and interact with this code directly in the browser without the need to clone it to your local machine. Hence its required for ease of code and testing and thus needs to be added in the repo for community benefit!

### Anything else?

Adding this feature will help open-source contribution, testing and deployment much easier for developers.

Kindly assign this issue to me so that i can add Gitpod environment in the readme.

**Comment by n8maninger** [comment]
Adding a config file for such a niche use case isn't something we're interested in at this time. If there's more demand from the community in the future, we can revisit it. For now, I'm closing this issue.
