### ISSUE TITLE
Alerts Filtering - Might want to add an ALL Filter.

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#197]
### Description

You might want to add an all filter which would be the default.

<img width="385" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/c13957d3-818b-433a-9200-dec26b2e083d">

### Version

0.2.1 Beta 1

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

### Anything else?

Testnet

**Comment by n8maninger** [comment]
Added in #234
