### ISSUE TITLE
failed to listen on API address

### ISSUE THREAD

**Issue by rafaeuw** [SiaFoundation/hostd#202]
### Current Behavior

When the user hits the "seed" provided by the program, it closes unexpectedly and shows an error in the log that is
``{"level":"fatal","ts":1698806550.1921146,"caller":"hostd/main.go:312","msg":"failed to listen on API address","error":"listen tcp: lookup localhost on [fe80::96ea:eaff:fea8:1c1c]:53: no such host","address":"localhost:9980"}
``

### Expected Behavior

Everything should go normally, without errors and finalizing the registration.

### Steps to Reproduce

1. Open hostd.exe
2. Insert your password
3. Enter the Seed Correctly
4. ***error***

### Version

v0.2.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Windows 11

**Comment by n8maninger** [comment]
Thanks for reporting. As a workaround, you can add `-http :9980` to your command

**Comment by rafaeuw** [comment]
A similar error occurs in **renterd** as well.

![image](https://github.com/SiaFoundation/hostd/assets/119011110/1021e0af-395d-4d08-9e9b-dea1b5e608ca)

**Comment by n8maninger** [comment]
Fixed in a9c197a926e46817b69bae4168db2b37467706f2
