### ISSUE TITLE
Hostd should not allow you to announce without a port.

### ISSUE THREAD

**Issue by skunk-ink** [SiaFoundation/hostd#204]
### Current Behavior

It is possible to announce your host without a port. This should not be allowed to avoid new user frustrations.

### Expected Behavior

A user should not be allowed to announce without setting a port. It might be good to even have it default to the port `9982` if one wasn't specified and confirm with the user that is the port they would like to announce on. There should also be a little information icon that tells users they should be announcing the RHP2 port which is 9982 by default.

### Steps to Reproduce

1. Announce without a port number specified

### Version

V2.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu Server 22.04 LTS

**Comment by n8maninger** [comment]
This is fixed in #195, will release v0.2.1 soon

**Comment by skunk-ink** [comment]
Ah awesome. I tried looking to see if it was addressed or not but missed it. I'm updating the docs to specify that this needs to be done as well 👍
