### ISSUE TITLE
Add date ranges to the contact tab

### ISSUE THREAD

**Issue by AZComputerSolutions** [SiaFoundation/hostd#212]
### Description

Add date ranges to the contact tab

right now if I sort by expiration date, I see a bunch of contracts that have already expired going back to the beginning of time.  This is not really helpful.  I want to see a list of contracts that are about to expire but I have to hit the next next next button to get to active contacts that are about to expire.

### Version

0.2.2 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
If you sort by expiration date ascending and filter by "active" you'll get a list of contracts about to expire.
![Screenshot 2023-11-19 at 11 59 56 AM](https://github.com/SiaFoundation/hostd/assets/5544150/d6deaeb5-a7ae-491e-9dbb-107d720e1c70)
