### ISSUE TITLE
Onboarding wizard should be optional, with possibility to switch it off

### ISSUE THREAD

**Issue by serveriukai** [SiaFoundation/hostd#216]
### Current Behavior

It's not possible to switch-off onboarding wizard on announced, running hostd instance.
Wallet is currently "underfunded" with less than 5000SC, so wizard  demands funding without a possibility to switch it off.

### Expected Behavior

Should be possible to close the wizard window

### Version

v0.2.2-beta.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Debian 12

**Comment by n8maninger** [comment]
@alexfreska can you change the onboarding wizard to > 0 SC
