### ISSUE TITLE
Clickable contract links in the contracts tab that opens siascan in a seperate browsing tab

### ISSUE THREAD

**Issue by AZComputerSolutions** [SiaFoundation/hostd#219]
### Description

It would be nice if you clicked on a contract if it brought up the contract in a separate browsing tab

<img width="1802" alt="image" src="https://github.com/SiaFoundation/hostd/assets/149719965/19db50da-44d4-44cc-889d-843e20e967a1">

<img width="1149" alt="image" src="https://github.com/SiaFoundation/hostd/assets/149719965/d4a581aa-f8c0-44c2-826f-7ddc1641a47f">

Right now you can copy the contact and go to siascan but it would be nicer if you could just click on the contract and it would launch siascan in a separate browser tab and bring up the contract.

### Version

0.2.2 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by alexfreska** [comment]
👍🏼 Added to next release
