### ISSUE TITLE
Onboarding wizard should be optional for existing users or possibility to switch it off.

### ISSUE THREAD

**Issue by azrielitay** [SiaFoundation/hostd#224]
### Current Behavior

I am an existing user that already have active contracts.
t's not possible to switch-off onboarding wizard on announced, running hostd instance.
Its blocking the Login screen
see attached picture.

### Expected Behavior

Should be possible to close the wizard window

### Steps to Reproduce

update to new version 0.2.2 and open browser.

### Version

0.2.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

windows 11

### Anything else?

See pic:
![image](https://github.com/SiaFoundation/hostd/assets/84931113/e6dacc52-a858-4acf-8920-7eefc69e6abe)

**Comment by azrielitay** [comment]
More info:
The Onboarding wizard is show again when restarting the hostd instance..

**Comment by n8maninger** [comment]
@alexfreska can we change the wallet funding to `confirmed + unconfirmed > 0`?

**Comment by n8maninger** [comment]
The onboarding wizard should be a little more reasonable after #234
