### ISSUE TITLE
RegisterAlerts Interface similar to RenterD

### ISSUE THREAD

**Issue by timrettop** [SiaFoundation/hostd#238]
### Description

If I understand things correctly,  hostd currently doesn't have the ability for an Alert to be registered via the API similar to renterd's api/bus/alerts/register.   This doesn't allow for external webhook registration testing to be completed, for example https://github.com/justmert/sia-telegram-alert-bot.  

Feel free to close if I'm off base with this request. 

### Version

master

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

docker

**Comment by n8maninger** [comment]
There’s an API endpoint to send a test request to a webhook handler https://api.sia.tech/hostd#4268fd05-f8b6-4c4d-9550-646f2d731877
