### ISSUE TITLE
Free space counting error in Resize Volume dialog window

### ISSUE THREAD

**Issue by serveriukai** [SiaFoundation/hostd#241]
### Current Behavior

Context: 6TB disk with couple of hostd volumes and some free space.

Create Volume dialog window, Size section free space counter:
0% of 759.20 GB available

The same counter in Resize Volume dialog window shows 6.00TB free space and allows to increase volume size up to 6TB.
Well, it's only possible only if growing of selected volume is made automatically removing / freeing space in existing volumes.

Or it's free space counter error.

### Expected Behavior

The same free space creating and resizing

### Version

v0.2.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Debian 12

**Comment by n8maninger** [comment]
@alexfreska can you change the remaining disk space on the resize dialog to match the create dialog?
