### ISSUE TITLE
Would be nice to have hostd version number visible in UI, also github downloads should be marked 

### ISSUE THREAD

**Issue by serveriukai** [SiaFoundation/hostd#245]
### Description

Had a trouble today trying to check hostd version on one of my hosts.
It's absent in UI, and even in downloaded from github hostd_linux_amd64.zip.

Was only able to guess 0.2.2 by download date. 

### Version

v0.2.2

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Linux

**Comment by n8maninger** [comment]
Version number should be visible by mousing over the Sia icon in the top left. It will say the commit for dev versions, but releases should have the release name.
 
![Screenshot 2023-12-21 at 7 51 16 AM](https://github.com/SiaFoundation/hostd/assets/5544150/ae4ab576-40c0-413e-8025-d9f21abe5e03)

**Comment by serveriukai** [comment]
Thanks, found it.
