### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#247]
### Current Behavior

"Copy to clipboard" is not working and throws an error in the browser console

```
TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')
```

### Expected Behavior

Text should be copied to clipboard

### Version

v1.0.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Chrome, Safari

**Comment by alexfreska** [comment]
odd, I removed a pollyfill, looked like it was no longer required (and works for me across all browsers): https://caniuse.com/mdn-api_clipboard_writetext

I'll add it back 👍🏼

**Comment by AZComputerSolutions** [comment]
Please note, the issue with the clipboard is on both Hostd and entered.
