### ISSUE TITLE
Document migration from `siad` to `hostd`

### ISSUE THREAD

**Issue by codekow** [SiaFoundation/hostd#270]
### Description

In PR https://github.com/SiaFoundation/hostd/pull/221 I see some work for migration tools, but no documentation and I'm not sure where the tools ended up for migration from `siad` to `hostd`

How does someone migrate from `siad` to `hostd`?
How does someone migrate from a `siad` wallet to `hostd`?

### Version

siad: 1.5.9
hostd: 1.0.1

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

- Linux 
- Docker 
- Podman

**Comment by n8maninger** [comment]
https://github.com/SiaFoundation/migrate-siad-host
