### ISSUE TITLE
Run `hostd` and `renterd` using a single blockchain file

### ISSUE THREAD

**Issue by codekow** [SiaFoundation/hostd#272]
### Description

I would like to know how to run `hostd` and `renterd` using the same blockchain on the same host to avoid duplicating storage space. Is that possible today?

Or just run the services required to query the blockchain on a single host where both `hostd` and `renterd` can query.

### Version

`hostd`: v1.0.1
`renterd`: v1.0.1 

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Linux / Docker / Podman

### Anything else?

Alternative: Avoid requiring the blockchain to be downloaded when using `hostd` or `renterd`

**Comment by n8maninger** [comment]
Closing as this is more of a question than an issue.

**Comment by codekow** [comment]
@n8maninger 

If doing this is not possible today, then it is a feature request.

Is it possible to do this today?

**Comment by n8maninger** [comment]
With a small amount of coding, yes, it's possible to do today. We will not be providing a combined app, though. Our current focus on Utreexo will eliminate the need to store the blockchain entirely. It's a much better solution for users who want to run more than one of the new ecosystem apps.
