### ISSUE TITLE
Background text in Address box suggests port 9882

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#283]
### Current Behavior

If you clear the Hostd > Configuration > Address box some background text in the box then shows, saying `my.host.com:9882`. This has lead a couple of users to announce mainnet sia on port 9882 rather than 9982.

### Expected Behavior

At a minimum, the mainnet binaries should display port 9982 to remove the confusion. If you want to be cute, it should display whatever the rhp2.address port is configured as (although this would be incorrect if there is port forwarding with port switching).

### Version

v1.0.0 amd mainnet

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

ClearOS 7.9

**Comment by alexfreska** [comment]
Thank you for the report, we noticed the increased number of users and the wrong port and figured this was the reason 😅. The fix is already in https://github.com/SiaFoundation/hostd/pull/281 and will be in the next release!
