### ISSUE TITLE
Add host score to hostd (some where)

### ISSUE THREAD

**Issue by AZComputerSolutions** [SiaFoundation/hostd#284]
### Description

Late last year all of a sudden I went from 18 tb of data stored down to nothing (just a few gigs of data).  After a bit of troubleshooting with Nate, it was discovered that my collateral multiplier was to low.  I think it was either 1 or 1.5 and that caused hosts to drop me as a storage provider.  It would be nice to have this score shown in hosted (the same one that renterd is using) so that host operators can do something about this issue before they lose data and not after.

### Version

Any Version

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by AZComputerSolutions** [comment]
This is tagged as done but I don't see the score anywhere on the latest build.  Can I ask where it is located?  I was expecting it in the status windows up in the top left when you move over the sia icon but don't see it.

**Comment by ChrisSchinnerl** [comment]
This wasn't implemented. Nate closed it as "not planned". 
The score that `renterd` gives a host is not the same across every instance of `renterd` and can't be shown in `hostd`.
Once we have a new explorer up and running + integrated into `hostd` we might be able to offer a better solution.
