### ISSUE TITLE
Persistent track keeping of integrity checks for contracts

### ISSUE THREAD

**Issue by larsfloe** [SiaFoundation/hostd#306]
### Description

Reacting to recent forum dialog on the status messages when doing integrity cheks on contracts where the more elegant and usefull solution to handle messages coming from the integrity check would be to store them ON the contracts panel for the host operator to keep track of how many sectors were last time checked and when and with what outcome. You loose the overview of what you've checked if you have more than like 10 contracts, and some hosts might want to really verify their contracts in order to be what SIA is all about having good hosts!

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

WIn10

**Comment by n8maninger** [comment]
This is part of changes I want to make with #85 and #25, so closing this as a duplicate

**Comment by larsfloe** [comment]
Hello Nate, all good. this suggestion came along from a dialog on the 
forum, where we concluded it was difficult to keep an overvies of which 
contracts already checked with which outcome and when - that overwiev 
sits in the message log, decoupled from the contracts view, so please 
also give it a thouhgt how from a hosts perspctive to follow the true 
state of you contracts and their sector health..  //br  lars

On 2024-03-14 16:41, Nate Maninger wrote:

> This is part of changes I want to make with #85 [1] and #25 [2], so 
> closing this as a duplicate
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/SiaFoundation/hostd/issues/85
[2] https://github.com/SiaFoundation/hostd/issues/25
[3] 
https://github.com/SiaFoundation/hostd/issues/306#issuecomment-1997754534
[4]

**Comment by n8maninger** [comment]
As I said, we plan to add this feature and it is already tracked by #85
