### ISSUE TITLE
failed to prune sectors: failed to delete all sectors.

### ISSUE THREAD

**Issue by azrielitay** [SiaFoundation/hostd#309]
### Current Behavior

Application crush on startup:
PANIC   contracts       failed to process contract actions      {"error": "failed to expire contract sectors: failed to prune sectors: transaction failed (attempt 1): failed to prune sectors: failed to delete all sectors", "stack": "go.sia.tech/hostd/host/contracts.(*ContractManager).processActions\n\tgo.sia.tech/hostd/host/contracts/actions.go:80"}
panic: failed to process contract actions

goroutine 122 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc0024e8b80?})
        go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002284270, {0xc000d99480, 0x2, 0x2})
        go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc000523040?, {0x7ff6262eb78a?, 0x7ec8c8?}, {0xc000d99480, 0x2, 0x2})
        go.uber.org/zap@v1.26.0/logger.go:284 +0x51
go.sia.tech/hostd/host/contracts.(*ContractManager).processActions(0xc000523040)
        go.sia.tech/hostd/host/contracts/actions.go:80 +0x2c7
created by go.sia.tech/hostd/host/contracts.NewManager in goroutine 1
        go.sia.tech/hostd/host/contracts/manager.go:527 +0x3f8

### Expected Behavior

Run normally. 

### Steps to Reproduce

Start application

### Version

1.0.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Windows 11

**Comment by azrielitay** [comment]
Going back to  hostd V1.0.1 the issue is resolved.

**Comment by danielringch** [comment]
I have exactly the same issue, switching back to 1.0.1 worked for me, too.
