### ISSUE TITLE
Recreate and fix volume response hanging in hostd

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/hostd#347]
- Mentioned by wings on discord: https://discord.com/channels/809849352516141067/827641929008152635/1206921984844365834
- Have not seen this issue, try to recreate by configuring and growing large volumes.

![Image](https://github.com/SiaFoundation/hostd/assets/1412796/d94d4a2a-d4a2-466b-a7d1-5d4ad175d6d9)

**Comment by alexfreska** [comment]
@n8maninger have you ever seen this where the list shows hangs on the skeleton - maybe when configuring a large test host? It would have to be from the /volumes request hanging. If not, we can probably close it out until we get another report.

**Comment by alexfreska** [comment]
Actually all requests seem to slow down when allocating multiple large 1TB+ volumes. If wings was configuring massive volumes they this does seem to occur.

**Comment by n8maninger** [comment]
I haven't seen this before, including when allocating volumes over 100TB. Maybe it's environment-specific though? Allocating a volume is pretty IO-intensive on both the metadata drive and the data drive.

**Comment by alexfreska** [comment]
Going to close this for now, until we notice during our large node testing or receive more similar reports.
