### ISSUE TITLE
Underflow panic after running for 20-30 minutes

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/hostd#361]
### Current Behavior

![image](https://github.com/SiaFoundation/hostd/assets/72828450/518d9c3f-f2e1-423d-8886-f1ccc4d2e2bd)

### Expected Behavior

No panic

### Version

v1.0.4

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Windows 10

**Comment by n8maninger** [comment]
This ended up being a consistency issue from a restored database and not a bug in `hostd`
