### ISSUE TITLE
Fix incorrect pending transaction value

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/hostd#399]
- Pending transactions shows incorrect siacoin transfer value until confirmed
- https://discord.com/channels/809849352516141067/827641929008152635/1243532719166853221
- Double check renterd calculation as well.

**Comment by serveriukai** [comment]
adding screenshot here:
last three transactions were all -1000 SC
![strange-transfers](https://github.com/SiaFoundation/hostd/assets/73857292/0b782ec2-d45d-413d-9e89-134aa0c8bfe0)

**Comment by alexfreska** [comment]
@n8maninger the siacoin values are calculated as `BigNumber(t.inflow).minus(t.outflow)` for both pending and regular transactions - is this approach incorrect? I just tested sending 50 SC, and it looks like inflow is 49 and outflow is 0 in the pending transaction data.
<img width="1857" alt="Screenshot 2024-06-12 at 4 10 45 PM" src="https://github.com/SiaFoundation/hostd/assets/1412796/58492e48-3b9f-4e4e-8dfa-a7caee4de280">

**Comment by alexfreska** [comment]
Ah interesting, @n8maninger if I do the opposite and send 100 siacoin to `hostd`, the incoming 100 siacoin value shows as inflow 100, outflow 0.
