### ISSUE TITLE
Fatal error siascan unavailable.

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SiaFoundation/hostd#427]
### Current Behavior

Reported by someone else on Discord;
If siascan is for some reason unavailable, a fatal error prevents hostd from starting.
https://discord.com/channels/809849352516141067/827641929008152635/1258327262978375720

### Expected Behavior

FIAT related features to be unavailable with possibly a banner/alert warning the user. hostd should be able to start regardless.

### Version

v1.1.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Linux and Windows

### Anything else?

Unsure if this is also the case for other the programs

**Comment by n8maninger** [comment]
Fixed by #430
