### ISSUE TITLE
Could remove `block_id` on `wallet_transactions`?

### ISSUE THREAD

**Issue by kocoten1992** [SiaFoundation/hostd#436]
### Description

`select block_id from wallet_transactions where block_id != null;`

The result is empty, if this field is useless, may I remove it via migration (and some of the code related)?

### Version

v1.1.1

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Debian 12.6

**Comment by n8maninger** [comment]
That column is not useless. It’s used to revert transactions during a reorg. 

https://github.com/SiaFoundation/hostd/blob/d77583ed4e7a5f5f404cce22b8061ef8dd6396bf/persist/sqlite/wallet.go#L93
