### ISSUE TITLE
The stated cost in the Announce dialog can be NaN

### ISSUE THREAD

**Issue by telestrial** [SiaFoundation/hostd#442]
### Current Behavior

While running hostd on the zen test net, clicking the announce button presents a dialogue that says:

> Announcing will cost NaN TS.

![Screenshot 2024-07-29 at 2 07 03 PM](https://github.com/user-attachments/assets/e5c1baeb-dfea-4eec-b8dd-9b5c61947855)

### Expected Behavior

I would expect NaN to be a number--the cost of the announcement.

### Steps to Reproduce

1. Run terminal HostD (zen network)
2. Open the localhost UI
3. Configure your settings
4. Click the Announce button in the upper right

### Version

v1.1.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

macOS Sonoma 14.5

### Anything else?

Chrome Version 126.0.6478.183

**Comment by n8maninger** [comment]
Seems like this got fixed at some point
