### ISSUE TITLE
Close create and resize dialog while initializing volumes

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#48]
### Description

I created a new volume of 10TB. Initially, the volume is added to `/volumes` with a `status` of "creating". The `maxSectors` field is updated as the volume initializes. Once the volume is finished, the `status` changes to "ready".
![Screenshot 2023-05-23 at 10 09 53 AM](https://github.com/SiaFoundation/hostd/assets/5544150/7f478e52-6cb2-42be-a8b5-c86744b94a82)
![Screenshot 2023-05-23 at 10 14 11 AM](https://github.com/SiaFoundation/hostd/assets/5544150/2d2390e1-613f-4998-ab33-af284b20dafc)

From a UX perspective, we should be able to close the volume and perform other tasks while the volume initializes in the background. Manually closing the dialog works but may hide a potential error. 

I don't know if this can be done easily in the UI alone. We might need to update the API to return immediately if the volume is successfully created and continue initializing it in the background. An alerts endpoint to track errors may be necessary. Thoughts?

**Comment by alexfreska** [comment]
We discussed this issue and are making the following changes:
- Change the volume create, resize, and delete endpoints to return immediately and dialogs to close immediately, with a possible error, then have the process continue in the background.
- Add alert endpoints to surface any background errors to the user via a global alerts interface.
- Add general volume errors to the table view.

**Comment by n8maninger** [comment]
The volume endpoints were changed and alert endpoints added by #66

**Comment by n8maninger** [comment]
Closing, will add new FU issue for alerts UI
