### ISSUE TITLE
Bug: Please switch back to version number instead of pull request number.

### ISSUE THREAD

**Issue by AZComputerSolutions** [SiaFoundation/hostd#485]
### Current Behavior

The version that shows up when you move over the sia logo now shows the pull request number instead of the version number like it did previously.  Which means if you want to know the version number you are running you need to go into github and look it up based on the pull version number.  Can we change this back to version number?  Thanx

![Image](https://github.com/user-attachments/assets/7e951565-7108-4a38-98e1-a15ef667fa26)

### Expected Behavior

Shows version number.

### Version

v2.0.0-alpha.3

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

**Comment by pcfreak30** [comment]
Pull request number? its showing the git commit hash which is kind of standard, especially when you are doing a custom build.

**Comment by AZComputerSolutions** [comment]
That seems inconsistent, up to this point it has always shown the version number.

**Comment by n8maninger** [comment]
You are correct. It will be fixed in the next release. Thanks for the report 👍
