### ISSUE TITLE
Incorrect amount of available space

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#49]
### Current Behavior

when adding a volume, it does not accurately indicate the amount of used space.

<img width="1183" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/2b769764-ff11-4802-959a-85f055321ffa">

You will note in the screen shot that I already have 9 TB of space used in two folders on the mounted volume but it is still offering me to create a 9 tb volume.

### Expected Behavior

as volume folders are created the amount of available space should drop.

### Version

0.1.0 Alpha 1

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
It isn't easy to detect free space on Linux and macOS because Sia creates empty sparse files. The simplest solution would be to fill the volume with random data on every OS. Determining up front whether the host has enough space to create the volume would be beneficial but drastically increase the provisioning time.

**Comment by rdwild** [comment]
it worked ok in sia host manager (my server was running windows at that time).

**Comment by rdwild** [comment]
It seems to me that hostd already knows what has been assigned to it via the volumes that are already loaded (see picture).  It knows the total volume so it should know what is left over space-wise.  I know that is not a perfect solutions but I think it comes close.

**Comment by rdwild** [comment]
I see this has been removed from the 0.2.0 milestone.  When is this going to be fixed?  I am using a raid array and this makes it very difficult to allocate space on a mounted drive that already has a volume already created.

If I run a df in ubuntu, I get:

<img width="539" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/2b575a0f-5c30-4f50-8ef0-becaa478c70e">

If I run an fdisk -l, it tells me I have just over 9.09 tb of space on the drive:

<img width="430" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/495598ad-4f24-4ccc-af91-014543c1dfb4">

But if I look at hosted it says that almost all of the space is used based on looking at total minus what I currently allocated.

<img width="587" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/b585bbd7-549e-4fcb-b88c-368270ed938a">

**Comment by n8maninger** [comment]
This goes back to the conversation about Linux and macOS using sparse files. The only viable way to fix this on those operating systems is to fill the volume with junk data when it's initialized or resized. That would effectively reserve the space on disk for `hostd`. There are some benefits to reserving capacity ahead of time. However, it comes with a significant trade-off: filling the volume with junk data increases the time it takes to initialize a volume by around 200x. 

I've created a draft PR to fix the issue: #158. I'll decide whether I want to merge it or close this issue by the end of the week.

**Comment by rdwild** [comment]
I would think it would just be a matter of keeping track of what is being allocated in hosted but maybe I am oversimplifying it.

**Comment by rdwild** [comment]
I don't agree, to get that number your just taking the total free space your getting from the OS and subtracting the volumes already created for that mount point to give you a space left.  hostd should know how much space was used up by the host volume it created.  It created the files.
