### ISSUE TITLE
Add CAD to currencies

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#50]
### Description

Is CAD currency going to be added to the list (it was available in the previous version.

<img width="347" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/cdf96ab2-5351-4a8e-8e53-c1eaf7418d42">

### Version

0.1.0 Alpha 1

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
Closed by #67
