### ISSUE TITLE
UI loading incorrect page

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#51]
### Current Behavior

when I hit the browser refresh button, the page refreshes to home but the URL still says whatever page you were at before you hit refresh.  

<img width="1520" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/8a164f0e-45cf-48c6-be8f-fbd50ab7a2fb">

### Expected Behavior

Hitting refresh should show you the same page your are currently on.you

### Steps to Reproduce

clicked on config
then clicked on the refresh button on the chrome browser.
URL says config but the home page is displayed. (see above image)

### Version

0.1.0 Alpha 1

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

windows 10, chrome browser

**Comment by n8maninger** [comment]
Closed by 131cf76
