### ISSUE TITLE
Docker image bugs

### ISSUE THREAD

**Issue by kttm25** [SiaFoundation/hostd#511]
### Current Behavior

The docker image bugs when the hostd.yml file is inserted. The following error is shown :

hostd-1    | failed to decode config file: yaml: unmarshal errors:
hostd-1    |   line 6: field syncer not found in type config.Config
hostd-1    |   line 10: field network not found in type config.Consensus
hostd-1    |   line 11: field indexBatchSize not found in type config.Consensus

### Expected Behavior

It must be possible to change the network and all the field in hostd.yml should work

### Version

v1.1.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Windows 11

**Comment by n8maninger** [comment]
This is expected behavior and not a bug. The config fields you are trying to use do not exist in v1.1.2 . To change the network in v1.1.2, you need to switch the image to `:latest-testnet`. If you need support, please join our Discord.
