### ISSUE TITLE
error decoding *chain.supplementedBlock: encoded object contains invalid length prefix

### ISSUE THREAD

**Issue by silviumc** [SiaFoundation/hostd#513]
### Current Behavior

hostd-2.0.0alpha4 does not start, hostd-2.0.0alpha3 did.
Can't go back to alpha3 because "failed to open database: database version 31 is newer than expected 30. database downgrades are not supported"

sia@k1stor:~> ./hostd 
INFO    hostd   {"version": "v2.0.0-alpha.4", "network": "mainnet", "commit": "d0a0432", "buildDate": "2024-11-20T17:21:07+02:00"}
panic: error decoding *chain.supplementedBlock: encoded object contains invalid length prefix (14110789110353583014 elems > 472 bytes left in stream)

goroutine 137 [running]:
go.sia.tech/coreutils/chain.check(...)
        go.sia.tech/coreutils@v0.7.0/chain/db.go:197
go.sia.tech/coreutils/chain.(*dbBucket).get(0x0?, {0xc0038abf80?, 0x1e00a40?, 0x0?}, {0x1858b60, 0xc0038bae80})
        go.sia.tech/coreutils@v0.7.0/chain/db.go:222 +0x1c5
go.sia.tech/coreutils/chain.(*DBStore).getBlock(0xc000167208, {0x0, 0x0, 0x0, 0x0, 0x6, 0x4f, 0xe6, 0xfe, 0x8d, ...})
        go.sia.tech/coreutils@v0.7.0/chain/db.go:309 +0xfd
go.sia.tech/coreutils/chain.(*DBStore).Block(0x0?, {0x0, 0x0, 0x0, 0x0, 0x6, 0x4f, 0xe6, 0xfe, 0x8d, ...})
        go.sia.tech/coreutils@v0.7.0/chain/db.go:649 +0x99
go.sia.tech/coreutils/chain.blockAndParent({_, _}, {0x0, 0x0, 0x0, 0x0, 0x6, 0x4f, 0xe6, 0xfe, ...})
        go.sia.tech/coreutils@v0.7.0/chain/manager.go:61 +0xbc
go.sia.tech/coreutils/chain.(*Manager).UpdatesSince(0xc000016008, {0x1fa, {0x0, 0x0, 0x0, 0x0, 0x6, 0x4f, 0xe6, 0xfe, ...}}, ...)
        go.sia.tech/coreutils@v0.7.0/chain/manager.go:431 +0x3d6
go.sia.tech/hostd/index.(*Manager).syncDB(0xc000160140, {0x185fff0, 0xc001588000})
        go.sia.tech/hostd/index/update.go:35 +0x1ca
go.sia.tech/hostd/index.NewManager.func2()
        go.sia.tech/hostd/index/manager.go:153 +0x248
created by go.sia.tech/hostd/index.NewManager in goroutine 1
        go.sia.tech/hostd/index/manager.go:138 +0x4d9

### Expected Behavior

I would expect alpha4 to start. I don't know if this is a bug or there is something wrong with my data.

### Steps to Reproduce

I had 1.1.x, then put 2.0.0alpha3 in place. It took *one month* to sync block or whatever, one month of grinding the hard-disk.

Then, it got stuck for one day at reading wallet 90.9%

I put alpha4 in place, that does not start at all because of that error.

Do I clean everything up, erase all data and start fresh?

### Version

2.0.0alpha4

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

openSUSE Leap 15.6

**Comment by mike76-dev** [comment]
Usually deleting `consensus.db` and re-syncing helps.

**Comment by n8maninger** [comment]
We do not recommend running alpha versions on Mainnet.
