### ISSUE TITLE
Auto-detect if consensus needs upgrading

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#544]
### Description

Hostd should autodetect if the consensus is no longer valid and delete any invalid consensus forcing a resync.

This is a particular issue when going from v1 > v2-alpha > v2-beta. It would be way easier and less error-prone for the user if this were automated.

### Version

v2.0.0-beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Debian 12

**Comment by pcfreak30** [comment]
tbh this sounds similar in principle to https://github.com/SiaFoundation/walletd/pull/205 which required a re-sync as well.

**Comment by n8maninger** [comment]
Already tracked by https://github.com/SiaFoundation/coreutils/pull/132.
