### ISSUE TITLE
UI Localization

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#56]
### Description

Currently in the hostd Overview screen, all graph use the US date format (mm/dd/yyyy). Please can they display in the localized date format. The format should be taken from either the server (better) or from the browser (best).

Guessing, but if you use the localized date format, you can also use the localised time?

### Version

v0.1.0-alpha.1 with fix at d4c887f

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
To add to this, we should double check we’re localizing everywhere in the UI: currency, dates, numbers (1,000 vs 1.000)

**Comment by n8maninger** [comment]
Closed by #67
