### ISSUE TITLE
Allow input of a Collateral multiplier of the Storage price as well as a value in SC

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#78]
### Description

Currently, when you change a storage price you need to remember to change your collateral. I think many people mentally just want to set collateral as a fixed multiple of Storage e.g. 1.5, 1.75, 2.00 and the UI could facilitate that. Then, as a host, you can set and leave your collateral policy and only ever adjust your storage price.

This logic could also be extended to the Maximum Collateral value.

### Version

v0.1.0-alpha.3

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
@alexfreska I don't want to support both collateral multiplier and manual collateral on the backend. I'm leaning towards changing the setting to `collateralMultiplier` and forcing hosts to set it as a percentage of their storage price.

**Comment by alexfreska** [comment]
@n8maninger yeah I also think the percentage makes more sense. I can adjust the UI input to be the percentage and maybe display the siacoin value below if that is useful.

**Comment by NickJH** [comment]
Personally I much prefer a multiplier, but others may differ. If you are unsure, is it worth putting it to the community?
