### ISSUE TITLE
It would be nice if there was an uptime status

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#92]
### Description

It would be nice if there was an uptime status maybe in home or in the sia icon in the top left hand side of the screen.

### Version

0.1.0 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment]
@alexfreska `[GET] /state/host` has `startTime` https://api.sia.tech/hostd#32ef7651-c2c1-43c6-89d3-f17c188b4667
