### ISSUE TITLE
Enable write caching to SSD

### ISSUE THREAD

**Issue by larsfloe** [SiaFoundation/hostd#94]
### Description

Looking at the asymmetrical upload/download performance of my own host, I got the following idea, that could overall improve SIA upload to hosts:

Expanding the internal SSD to a larger one – 1-2TBs have become kind of cheap.
Use some of that space in HOSTD assigning it to a separate volume, asking for a new HOSTD function: 

•    optionally to assign one of the volumes/drives (the SSD one) acting as primary drive/volume for  receiving of all incoming data that if space is available. If no space on the primary (cached) drive is data should settle like today.
•    when the host is not busy, working with uploads, that cached data should  be settled "sinking" (moved) onto the other volumes/drives freeing up primary drive (the cache)

By having cache on SSD directly in the HOSTD all hosts could seriously, combined contribute to improve uploads to SSD instead of HDDs, combing the SSDs speed with the HDDs capacity. By using SSDs instead of RAM (saw a discussion on RAM cache)  much much more cached storage can be made available. Building this could also be a great differentiator option for host competition.

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

win10

**Comment by rdwild** [comment]
I like the idea but it should be optional.  Even the option of adding a separate volume or drive.

**Comment by larsfloe** [comment]
Indeed, I think it should be optional but I don't know how it will be designed/coded.  Taking  it a bit further I think a few new parameters would be handy:

for each volume in the volumes list in the UI, add a "fill sequence" field and a "volume type" (ie. Cache or normal)

if the above is not changed by the user, HOSTD can just perform as per today. If the parameters are set, I envision:
HOST to fill up the volumes as per the sequence, and for any drives that are marked as "cache" a mechanism should move the data to the next volume in the list. 

That would enable also allocating some memory as a RAM drive for super fast caching, letting that data sink onto the next cache layer, perhaps a SSD, and when idle that can sink onto a spinner.. That would make uploads faster.

**Comment by PiotrZSL** [comment]
In theory you can do this with bcache / bcachefs.

**Comment by larsfloe** [comment]
I guess you are right - I am a windows host and I think volume 
management or a simple "fill strategy" should be made available in the 
client it self.

which drives to fill and how and how to balance - that would also enable 
the SSD cache, I'm promiting in the suggestion.

On 2024-02-12 21:17, Piotr Zegar wrote:

> In theory you can do this with bcache / bcachefs.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/SiaFoundation/hostd/issues/94#issuecomment-1939503701
[2]

**Comment by ChrisSchinnerl** [comment]
Tbh this feels like something that should be handled at a lower level than the application layer.
Afaik there are multiple battle-tested solutions out there (some on windows) which would allow you to get ssd write caching that `hostd` doesn't need to be aware of.

**Comment by larsfloe** [comment]
Hi Chris,

well... I think it depends. in IT there are always different ways of 
obtaining the same. Offering good functinality to hosts is key to grow 
the quality of the network. I'm sure the average host would appreciate 
not only the actual suggestion here, but also more enhancements that 
make hosting, easy, frictionless and reliable, so from that perspective 
it belongs right into the core, IMO.

br
lars

On 2024-02-13 10:12, Christopher Schinnerl wrote:

> Tbh this feels like something that should be handled at a lower level 
> than the application layer.
> Afaik there are multiple battle-tested solutions out there (some on 
> windows) which would allow you to get ssd write caching that hostd 
> doesn't need to be aware of.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/SiaFoundation/hostd/issues/94#issuecomment-1940850562
[2]

**Comment by ChrisSchinnerl** [comment]
We have given this some more thought but have come to the conclusion that adding ssd caching is out of the scope of `hostd`. That's because we try to keep a narrow scope and try to not reinvent things wherever possible.

If there is more demand in the future we could extend the official documentation with a guide on how to use specific third party tools with `hostd` to achieve ssd caching and we'd also be happy to accept contributions to our docs in the form of guides like that.

**Comment by larsfloe** [comment]
Hello Chris,

the foundation ultimately owns the road map. I'm just always happy to 
ideate around certain topics. On your note on off the shelf software to 
accomplish cached drives there are indeed such apps. I'll perhaps try 
one out and might decide to do a write up - could potentially even be 
under the small grants hat. let' me think.

But where the thought of the below actually came from is the lack of  
ack then, SIADs, now HOSTDs lack of proper volume managment/strategy 
where today if you have x drives the load is spread on all kind of 
equally.  I'll suggest something like this:

each volume is assigned a priority and filled accordingly - equality  
could be the default like today
a user could decide to priortize any filling sequence and rate.
a function to MOvE sectors from one drive should be made avaialble 
(today you can only prevent inflow, not move)

would I need to raise a feature request to have it decided or should I 
post in discord/hosting??

best
lars

On 2024-02-14 15:50, Christopher Schinnerl wrote:

> We have given this some more thought but have come to the conclusion 
> that adding ssd caching is out of the scope of hostd. That's because we 
> try to keep a narrow scope and try to not reinvent things wherever 
> possible.
> 
> If there is more demand in the future we could extend the official 
> documentation with a guide on how to use specific third party tools 
> with hostd to achieve ssd caching and we'd also be happy to accept 
> contributions to our docs in the form of guides like that.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/SiaFoundation/hostd/issues/94#issuecomment-1943959402
[2]
