### ISSUE TITLE
Add wallet scan progress

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/hostd#95]
### Description

Add progress for the wallet scan to the wallet page. The scan height can be retrieved from [GET /api/wallet](https://api.sia.tech/hostd#456e3b58-694d-4da2-9cea-b525193195ac).
![Screenshot 2023-06-26 at 11 18 21 AM](https://github.com/SiaFoundation/hostd/assets/5544150/67a8b384-8ccf-4ccf-a122-f30d0858b375)

**Comment by rdwild** [comment]
I'm not sure if it belongs here (I have added a new feature request so if it belongs here kill the other one 114) but there is a similar issue in the blockchain window.  it does not tell you the current block height your system needs to reach.

**Comment by n8maninger** [comment]
Fixed by #141
